### ISSUE TITLE
Assignment 2: Burtin’s Antibiotic Data

### ISSUE THREAD

**Issue by venkatrajam** [info-design-lab/Plaksha_Dataviz#2]
In the post-World War II world, antibiotics were called “wonder drugs,” for they provided quick and easy cures for what had previously been intractable diseases. Data were being gathered to aid in learning which drug worked best for which bacterial infection. Being able to see the structure of drug performance from outcome data was an enormous aid for practitioners and scientists alike. In the fall of 1951, Burtin published a graph showing the performance of the three most popular antibiotics on 16 bacteria.

The data used in his display are shown in attached Excel file. The entries of the table are the minimum inhibitory concentration (MIC), a measure of the effectiveness of the antibiotic. The MIC represents the concentration of antibiotic required to prevent growth in vitro. The covariate “gram staining” describes the reaction of the bacteria to Gram staining. Gram-positive bacteria are those that are stained dark blue or violet; whereas, Gram-negative bacteria do not react that way.

Present a graphical representation of these data and an accompanying written description of the graph.

(this assignment is a rerun of the Chance magazine's contest on the 100th birth anniversary of designer Will Burtin who published the first visualization of the data in 1951. Contest winners' submissions are [here](https://www.tandfonline.com/doi/pdf/10.1080/09332480.2009.10722957).)

**Comment by utkg26** [comment]
### Performance Comparison of the Most Popular Antibiotics 
**By: Utkarsh Garg**

![Antibiotic Performance](https://user-images.githubusercontent.com/94378831/173221943-a7e222bc-d3fe-44c2-8451-9652ec95eb82.jpg)


- The graphs compare the performance of Penicillin, Streptomycin and Neomycin against the most common bacteria divided into positive or negative categories depending on the gram-staining test's results
- The MIC Concentration (less the better) depicted on the log scale shows the concentration of the effective performance
- For the negative stain bacterias neomycin is the most effective across the board. 
- In the positive category there is no one precise antibiotic but penicillin performs best across 4 bacteria by a clear margin

**Comment by aravindbhaskar41** [comment]
Name : Aravind Bhaskar

![image](https://user-images.githubusercontent.com/11617265/173223028-7ccdb5d6-56f1-4f34-b626-2128a49c00d4.png)

![image](https://user-images.githubusercontent.com/11617265/173223327-dfa2839e-76d4-4cd8-9d8e-233c90e771f2.png)

- Have used the multi-bar chart for easy understanding 
- The positive and negative gram stain bacteria are represented in two different graphs. Haven't used any coloring for staining as the gram staining differentiates bacteria on whether they can retain the stain or not. 
- Have used a logarithmic scale of base 10 to depict the MIC 
- Less 1 ug/mL MIC is represented in a downward direction. Making it easy to spot the best antibiotics(lowest peak) for each bacteria 
- The title relates more to the bacteria rather than the staining process

**Comment by ranjan8manish** [comment]
Name: Manish Ranjan
![Assign2_mr](https://user-images.githubusercontent.com/96104376/173222258-87ecc750-a5c5-473c-a52a-d737329e5c8e.jpg)

1. Here I have used 2 horizontal stacked bar graphs to represent the quantity of each of the antibiotics (Penicillin, Streptomycin and Neomycin ) used for different types of bacteria.
2. First graph shows the "Negative Gram Staining" , where Penicillin is used in maximum quantity for different bacteria. The graph shows that the performance of Penicillin is the worst.
3. Second graph shows the "Positive Gram Staining" , where Streptomycin and Neomycin are used in more quantity for different bacteria. The graph shows that the performance of Penicillin is the best.

**Comment by sahilshaheen** [comment]
## Visualisation
![Burtin's antibiotic data visualisation](https://i.ibb.co/L1LZ48m/burtin-viz.png)

## Choices made as per objectives of the visualisation

- **Compare the effectiveness of antibiotics across various strains of bacteria**

  - I made the choice not to group bars by antibiotics (grouped bar chart) as it hampers the ability to compare the distribution of MIC across bacteria for each antibiotic (due to clutter). Instead, I have used plotted bar graphs of MIC on different columns of a facet grid for each antibiotic. The comparison of effectiveness of different antibiotics on a single strain can still be done using the vertical grid lines in the chart.
  - Log scaling on the dependent axes for effective comparison
  - ~Plotting 1/MIC instead of MIC (since lower MIC is better)~
This led to certain MIC values for Penicilin disappearing from the chart (due to their extremely small magnitude) and was not implemented in the visualisation

- **Compare effectiveness on positive vs. negative gram staining bacteria**
Simple grouping across the categorical axis in the chart is used to fulfil this objective

**Comment by subratsaxena** [comment]
Name: Subrat Saxena

<img width="768" alt="Brucella anthracis" src="https://user-images.githubusercontent.com/97718805/173227838-8b379f01-3f16-4112-a17d-0e4964d04879.png">

The data given has the following hierarchy:
1. We have **two classes** based on Gram Staining i.e. Positive or Negative
2. Under these two classes we have in total of **16 bacterias**
3. Each bacteria has its own reaction value with different **antibiotics**

Therefore, we needed a graph which could represent the data in the same hierarchial format along with the capability to compare the MIC levels. Therefore, this spyder graph seemed most suitable to do visualization for this data. 
The objective behind this data visualization is to enable user to compare different anti-biotics and their effect on different bacterias and this graph serves the purpose really well.

**Comment by lohkna007** [comment]
<img width="822" alt="Screenshot 2022-06-12 at 4 32 55 PM" src="https://user-images.githubusercontent.com/44726964/173230072-8741bf70-c59b-41fa-b77b-8568e27d26d7.png">



Name: Gaurav Lohkna
Assignment: 2 

Description of the graph:

- I have used the multi-bar graph so that it is easily distinguishable in terms of the MIC of each drug
- Used two separate graphs to understand the trend in both the positive and negative gram staining
- Instead of showing a linear trend I have shown a logarithmic trend 

There is a trend that is visible in both the negative and positive gram staining when visualized separately. In the negative gram staining, Neomycin is much less effective as compared to the other two, and in positive gram staining, Penicillin seems to be much less effective than the rest of the two.

**Comment by jaisal14** [comment]
![Sheet 2](https://user-images.githubusercontent.com/102915270/173233800-4090fe80-84bf-4c70-86fd-3085a4d558c5.png)

In the above graph, I have used three horizontal bar charts
1. The color coding represents two classes, Positive and Negative of gram staining (Used color blind palette)
2. There are three antibiotics for which we have MIC values which denote the effectiveness of antibiotics. Annotated these values for better comparison
3. I have used a logarithmic scale as the data was skewed due to large values for effective comparison

Tool used: Tableau

**Comment by akash-chowdhary** [comment]
![image](https://user-images.githubusercontent.com/93519610/173233818-e831f51f-9bd3-4856-915a-c212e220c6f1.png)
![image](https://user-images.githubusercontent.com/93519610/173233841-5e668035-084d-48cc-a744-2a66c7aee41c.png)

Name: Akash Chowdhary

Observations:

- Used a radar chart to compare the efficiency of each antibiotic against each bacteria. The two separate graphs compare positive and negative gram staining

- Used a logarithmic scale of base 10 to depict the minimum inhibitory concentration (MIC)

- For negative gram staining, we observe higher effectiveness of Neomycin when we compare the concentration required for active growth. The other two antibiotics are within the Neomycin (green line)

- For positive gram staining, we observed penicillin to be more effective against most bacteria except for two bacterias

**Comment by sehaj1001** [comment]
Name: Sehajpreet Kaur

<img width="843" alt="gramstain" src="https://user-images.githubusercontent.com/55667241/173236013-39a1dd4a-f306-4f67-ba5e-9f2c92adf163.PNG">

Description:
The chart used is a stacked bar chart. A logarithmic scale of base 10 depicts the minimum inhibitory concentration (MIC). This chart allows for comparison not just within a particular antibiotic but also across. Lower the MIC, better the effectiveness. Penicillin is more effective for positive gram straining and neomycin for negative gram straining.

**Comment by rishav-gupta** [comment]
Name: Rishav Gupta

<img width="335" alt="positive2" src="https://user-images.githubusercontent.com/22471213/173236370-8fe35c24-9612-4976-b51a-a8716ed0c3b7.PNG">
<img width="329" alt="negative2" src="https://user-images.githubusercontent.com/22471213/173236375-c4e519a9-d947-488c-855c-0616c66a16c5.PNG">

Description:
A stacked column chart is used to compare across antibiotics and also see each antibiotic in detail. A logarithmic scale of base 10 shows the MIC (or the effectiveness of each antibiotic). For positive, penicillin seems to be more effective while for negative, neomycin has the highest effectiveness.

**Comment by tanyaahuja147** [comment]
![image](https://user-images.githubusercontent.com/32067469/173240590-c0220727-fa4f-4e76-bad8-6770af40c756.png)
The Scale has been normalized before plotting. A simple line chart is used to visualize the effects .Penicillin is an effective drug in negative gram staining. 
![image](https://user-images.githubusercontent.com/32067469/173240702-70a171ef-16e2-478a-aef8-cb5e8bef7144.png)
Streptomycin is an effective drug in positive gram staining

**Comment by datababa1** [comment]
Name - Apratim Chandra Singh

![Neomycin](https://user-images.githubusercontent.com/91920461/173243736-e8a60f40-ba91-4e72-ba18-3b0850510a4d.JPG)
![Pencilin](https://user-images.githubusercontent.com/91920461/173243740-a45210b1-dccd-45a9-b3ba-821798b7e2fa.JPG)
![Streptomycin](https://user-images.githubusercontent.com/91920461/173243745-fbc170aa-f3fb-45d9-8ee8-c341d12c5f2b.JPG)


Observations :-

- The data is segmented by antibacterial drug instead of positive and negative gram staining

- The positive color is representative of the actual color on positive staining thus creating a visual cue

- Sorted the data in negative and positive direction and also provided legend as means of identification along with enclosing the axis title in the respective gram staining to allow the reader to understand the staining by visual identification since in several data points, the bar is not clear

- As lower the MIC, the more effective is the drug thus for positive gram staining - Penicillin is the most effective whereas for negative staining - Neomycin is the most effective

**Comment by arnav-tlf** [comment]
Name : **Arnav Sharma**

![PositiveGramStaining](https://user-images.githubusercontent.com/92753142/173243922-21db7173-11e7-4f90-b4f5-d6c1e481dbbf.jpg)
![NegativeGramStaining](https://user-images.githubusercontent.com/92753142/173243926-9bc911be-f2bd-455d-96ab-de0396dc9f04.jpg)

Description : 

- There are two charts - one for Positive Gram Staining and another for Negative Gram Staining.
- The x-axis is segmented into 3 parts representing the three Antibiotics. The reason for plotting the antibiotics on x-axis and not the bacteria is that it makes comparison between the effects of antibiotics on different bacteria easier.
- Penicillin is the most effective anitibiotic for inhibiting Gram-positive bacteria whereas Neomycin is the most effective antibiotic for inhibiting Gram-negative bacteria.

**Comment by pragun445** [comment]
Name - Pragun Aggarwal 

<img width="769" alt="Screenshot 2022-06-12 at 11 19 50 PM" src="https://user-images.githubusercontent.com/95849397/173247334-f71a8b2e-2612-4b04-ab3d-8eb802776b21.png">
<img width="637" alt="Screenshot 2022-06-12 at 11 13 48 PM" src="https://user-images.githubusercontent.com/95849397/173246796-4ea90ebd-3125-415e-8a12-64cecb10eff4.png">
<img width="667" alt="Screenshot 2022-06-12 at 11 15 40 PM" src="https://user-images.githubusercontent.com/95849397/173246970-0654a28c-ada2-4d9e-8067-a7b40effe0e7.png">


- Excel Column Charts have been created which shows the data of the penicillin, streptomycin and neomycin datasets with respect to various bacteria. 

- For positive gram straining - penicillin is the most effective whereas for negative gram straining - neomycin is the most effective.

**Comment by josephbenofficial** [comment]
Joseph Ben

![image](https://user-images.githubusercontent.com/66313320/173244785-130e2983-75f9-4ea6-830a-c4170fb3567c.png)

![image](https://user-images.githubusercontent.com/66313320/173244794-00667589-f700-4d09-ae7a-9fb88ba8d464.png)

Created two graphs for two classes. Used colours red and green to represent positive and negative classes respectively. Created a spider graph as it made the analysis easier and plotted on the logarithmic scale.

**Comment by yasirulhadi** [comment]
<img width="988" alt="Screenshot 2022-06-12 at 10 43 00 PM" src="https://user-images.githubusercontent.com/29412002/173245130-b0f8f627-3359-4bb5-bbf4-de4e6377766c.png">

Name: Yasir ul Hadi

Observations:

In the above graph, I used three horizontal bar charts respectively for Pencilin, Streptomycin & Neomycin.

- I used purple for positive gram staining and pink for negative gram staining.
- Major insights are : If bacteria is gram positive,Penicillin & Neomycin are most effective and If bacteria is gram negative,
Neomycin is most effective
- I used logarithmic scale on x axis to represent the Minimum Inhibitory Concentration

**Comment by pawanreddy-u** [comment]
Name: Pawan Reddy Ulindala
![image](https://user-images.githubusercontent.com/49510297/173244858-b829107c-25cb-4d86-8beb-7af33f8fa8b5.png)
![image](https://user-images.githubusercontent.com/49510297/173245014-23bc1624-0ee2-4b05-96b0-a4605380edab.png)
![image](https://user-images.githubusercontent.com/49510297/173245262-cbe3c93f-ab32-4cf8-817c-9e025b8e167f.png)

**Comment by 04kaushal** [comment]
**Name - Kaushal Kishore**

![image](https://user-images.githubusercontent.com/50120019/173245452-9d428b6e-db72-4749-9a5c-222ebacdc618.png)


**Details** 
Tool - Tableau
Chart Type - Bar Chart 

**Description** 

- All values for minimum inhibitory concentration (MIC) have been normalized to a logarithmic scale (log10).
- For representation purposes & uniform scaling, we took a range from -4 to 4 (Values already in the log).
- I have used a bar chart and separated each antibiotic into different columns for a clear understanding of w.r.t. bacteria type.
- The breakdown has been done color-wise for Gram staining (Positive / Negative) and implemented for each antibiotic.
- From visualizations, we observe that penicillin is more effective in positive staining while Neomycin has the highest effectiveness for negative staining.

**Comment by m-saiteja** [comment]
Name: Sai Teja Muliki

![image](https://user-images.githubusercontent.com/95857704/173246580-50bb21ec-f242-4245-a93e-5a852a7cc3ba.png)
![image](https://user-images.githubusercontent.com/95857704/173246616-1532dff5-385c-4f16-8bd1-aaa8c2718368.png)

A stacked bar plot has been used to compare across the antibiotics. The lesser the proportion of the drugs, the better the efficacy.
From this, we can conclude that for Positive Gram Strain, Penicilin is the most effective while for Negative Gram Strain it is Neomycin.

**Comment by abhishekanandiimr** [comment]
Name: Abhishek Anand

![Negative](https://user-images.githubusercontent.com/54315915/173246273-3ce4955d-a81b-4454-aae4-226b7d867f4d.PNG)
![Positive](https://user-images.githubusercontent.com/54315915/173246276-eeaa7b75-4ac0-435e-8c54-73f6a27feb7d.PNG)

Tool Used - Power BI

Description

- All values for minimum inhibitory concentration (MIC) have been normalized to a logarithmic scale (log10)
- Actual value of MIC has been mentioned at the end of the bar
- Penicillin is the most effective antibiotic for Positive Gram Staining bacteria 
- Neomycin is the most effective antibiotic for Positive Gram Staining bacteria -

**Comment by Apoorva2908** [comment]
Name : Apoorva Shekhawat

Chart type : Horizontal Bar

![image](https://user-images.githubusercontent.com/87797734/173246716-518fd876-1f99-44bf-a966-ba8862f1705b.png)

![image](https://user-images.githubusercontent.com/87797734/173246859-44cc4c66-7551-4735-bd0f-c89b9cc8b126.png)

Description:

- The visualization shows the effective comparison of the three antibiotics against each other.
- Also keeping the scale same for positive and negative gram, they can also be compared.
- Penicillin is extremely ineffective as an antibiotic for gram negative bacteria whereas it does fairly against gram positive.

**Comment by Lakshna1295** [comment]
Name - Lakshimi Naraayani

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/100415415/173246848-65a5d198-2922-462f-ba33-98bf7cf2149d.png)

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/100415415/173246858-7e5d9d62-dd12-44bb-b478-0077130197b4.png)

Description:
From the bar plot, it is observed that Penicillin is most effective for Positive Gram Strain and Neomycin is effective for Negative Gram Strain.

**Comment by Ramsai9ch** [comment]
**NAME: RAMSAI REDDY CHAMAKURA**

### Comparison of the Most Popular Antibiotics Performances
Chart Type: **WaterFall Chart**

[
![image](https://user-images.githubusercontent.com/95616516/173247342-80aa9a76-3ede-46e5-97fe-87a4a56e4ff0.png)
](url)

[
![image](https://user-images.githubusercontent.com/95616516/173247333-4e6b2695-7902-432a-93b8-1315ae3d8d33.png)
](url)

Description:

- For representation purposes, All values for minimum inhibitory concentration (MIC) have been normalized to a logarithmic scale (log10)
- Most effective antibiotic for Positive Gram Staining bacteria is Neomycin
- Most effective antibiotic for Negative Gram Staining bacteria is Penicillin

**Comment by JazBern** [comment]
Name : Jasmine Bernard
<img width="771" alt="Neg_GS" src="https://user-images.githubusercontent.com/22408878/173246382-4e51a42d-a788-42b0-b71e-0384456506e4.png">
<img width="796" alt="Pos_GS" src="https://user-images.githubusercontent.com/22408878/173246393-ce8c9d89-f68c-4ca0-a627-ecc98b48abce.png">

Description 

1. Used spline charts to represent the MIC measures for the three antibiotics on base-10 logarithmic scale.
2. Two separate graphs to represent positive and negative gram staining.
3. For gram-negative, it is clear from that graph that Neomycin has the lowest value for all bacteria.
4. For gram-positive, Penicillin performs better in 4 out of the 7 cases.

**Comment by BRupani** [comment]
Name: Bhawna Rupani
Visualization Design: Facet Horizontal Chart

![image](https://user-images.githubusercontent.com/95839849/173247551-16cd68ba-a95f-4bb9-ba43-e2db10852c45.png)

Description:
1. Most effective drug for negative gram stain is Penicilin.
2. Neomycin works for both, performs best for positive gram stain. 
3. Streptomycin works for both positive and negative gram stain but is more effective for positive case.

**Comment by LogeshKG** [comment]
Name: Logesh Kumar G
![image](https://user-images.githubusercontent.com/83027002/173247841-73fb92b4-02a0-49d4-8087-e64c020221a0.png)
![image](https://user-images.githubusercontent.com/83027002/173247847-99b3d08b-6fe6-4b0a-a614-3ca57fe226c2.png)

Description:
1. Used a filled radar chart to represent the MIC measures for the three antibiotics
2. Separate graphs for both positive and negative gram staining
3. Neomycin is effective in case of Gram-Negative staining
4. Penicillin performs better for Gram-Positive staining

**Comment by devashreepatel** [comment]
Name- Devashree Patel

![WhatsApp Image 2022-06-12 at 11 43 16 PM (1)](https://user-images.githubusercontent.com/48258439/173247725-932cf818-2a3d-4db5-8cc2-898d3d67354f.jpeg)
![WhatsApp Image 2022-06-12 at 11 43 34 PM](https://user-images.githubusercontent.com/48258439/173247737-37871d42-caa0-4e6c-868d-63969d8f1d41.jpeg)

Description:
1. In the first graph it is clear that Penicillin is performing better for negative gram staining bacteria.
2. In the second graph, we can see that Neomycin is most effective for positive gram staining bacteria.

**Comment by Harleen8-Bagga** [comment]
![bacteria](https://user-images.githubusercontent.com/53442613/173248548-5235c7b9-4ab5-436f-9039-b84f30e8c998.png)


1.Grouped all three (neomycin, penicillin, streptomycin) and stacked their 16 bacteria on the y-axis.
2.This way I am able to compare all the antibiotics within the context of all the 16 bacteria.
3.Classified negative as those with smaller widths and positive as ones with larger width.

**Comment by SmrutiShirodkar** [comment]
Name: Smruti Shirodkar

![Butin's MIC Negative](https://user-images.githubusercontent.com/95904559/173248124-f0c288b9-379e-4481-9215-fa7aecf9f595.png)
![Butin's MIC Positive](https://user-images.githubusercontent.com/95904559/173248129-803ec95f-c2cb-4d3f-b6e2-5646a2c03117.png)

Description: 
1. In the above graph, I have used two horizontal bar charts with Positive and Negative gram staining
2. The color coding in each graph represents the antibiotics, Penicilin, Streptomycin and Neomycin 
3. For the three antibiotics we have MIC values which denote the effectiveness of antibiotics on a logarithmic scale
4. Neomycin performs better among the three antibiotics for inhibiting the Gram-negative bacteria
5. Penicillin performs better in 4 out of the 7 cases among the three antibiotics for inhibiting the Gram-positive bacteria

**Comment by uneetkumarsingh** [comment]
![a1](https://user-images.githubusercontent.com/79808433/173253902-53b0e836-fc17-49a7-91c0-18032e90170c.png)

Description:
1. Instead of MIC Levels, inverse of MIC levels have been plotted on log scale. This is because smaller MIC levels indicate more effectiveness and thus longer bar will intuitively indicate more effectiveness of the drug
2. Since Gram Positive bacteria turn stain from blue to violet, they have been represented with shades of blue. 
3. Similarly, Gram Negative bacteria turn the stain to red, they have been represented with shades of red. 
4. Extremes of axis representing inverse of MIC levels have been labelled as Most effective and Least effective to ease graph interpretation.
5. Scales and range of x axis in both subplots have been kept same so that efficacy can be compared across the subplots

**Comment by udays2** [comment]
Name: Udaya Bhaskar Vaddi

Gram Staining - Positive
![dp](https://user-images.githubusercontent.com/69588471/173252520-c79e6b9e-d919-43b8-8abb-80d725183b71.png)

Gram Staining - Negative 
![dn](https://user-images.githubusercontent.com/69588471/173252534-b90b9742-347d-4a6e-a386-581db6a0a3b2.png)

Description:
1. The legend on the right side of the visualization gives the names of the bacteria.
2.  The MIC(Minimum Inhibitory Concentration) level of antibiotics is on the y-axis increasing towards the bottom.
3.  The scale is different for every column and we can compare the drug's concentration used for the bacteria.

**Comment by Riikon** [comment]
Name: Arun Sar

![Assignment Final 2](https://user-images.githubusercontent.com/3482260/173253437-3170d9d0-93d2-4544-9303-a9e8fc3ce750.png)


1. Before plotting, the data has been normalized since the range for MIC was too large. Formula used was: (X-Xmin)/(Xmax-Xmin)
2. The Gram Negative and Positive bacteria have been separated into two separate groups, on the same graph. Gram Negative Bacteria have been named using violet while Gram Positive Bacteria have been named using Green. This way an extra dimension was added to the visualization which allowed keeping all the data on a single bar graph which would facilitate easy comparison.
3. Since, lower MIC level implies more effectiveness, the axis has been named accordingly to show this important fact.
4. Three different colors have been used for each of the antibiotics for easy of differentiation while studying the visualization. Penicillin has been colored blue, Streptomycin as red and Neomycin as green. The same has been mentioned in the legends.

**Comment by 01supriya** [comment]
Name: Supriya Kumar Mishra
![image](https://user-images.githubusercontent.com/96125724/173253839-aa99a0dc-249b-45ca-80d7-68e13e410fbf.png)
![image](https://user-images.githubusercontent.com/96125724/173253846-3ed1adde-1db4-4cb4-8128-68b781f884dd.png)

**Comment by taniadaw** [comment]
Name: Tania Dawra
![image](https://user-images.githubusercontent.com/96387296/173253695-b5c54c88-1e56-49d0-82b8-70c04a2d9890.png)

Description:
- The graph has been made with grouping the various antibiotics using Bacteria and Gram Staining. This allows for effective 
comparison of the three antibiotics.
- Antibiotics with least MIC values are most effective.  It can be seen that Penicillin is highly ineffective as an antibiotic for gram negative bacteria but effective for gram positive bacteria.
- Subdivision into two categories with appropriate colors helps in comparison for efficacy of antibiotic against gram positive and gram negative bacteria.

**Comment by sarthakvarora** [comment]
<img width="575" alt="Screenshot 2022-06-12 at 3 17 21 PM" src="https://user-images.githubusercontent.com/58519757/173255850-e4484be9-3816-4387-81e9-58376de09e20.png">

Here's the thing! I personally love stacked charts, but often, the 100% stacked chart lacks some functionality which the other chart fulfils. For instance, in a 100% stacked chart, we are easily able to compare the efficiency of the antibiotics, but the metric value is lost. Hence, I created this chart where I stacked two stacked charts together, where the chart below fulfils the comparison and the chart above manages to give a sense of the metric value. Here are some other approaches and ideologies and inferences:

- I sorted the values from negative to positive, so that the chart can capture patterns in values which exist due to Gram Staining. And as predicted, we can see in the graph below that for Gram Negative cases, the value of MIC for Penicillin is high, while the MIC values of Neomycin and Streptomycin dominate the graphs for Gram Positive cases. This pattern is being missed in the chart above.
- Tilting the antibiotic names to 90 degrees ensures that it is being used by both charts, and by removing borders, I also establish a relationship between the two charts, thus creating continuity while maintaining minimalist design.
- The colors for negative and positive are chosen to enable the users to access the meanings of the depiction with ease.
- While the small insignificant values collect to the tips of the bar chart, their values lose relevance. If they still require to be shown properly, one can drag around the values on the chart to generate visibility.

**Comment by krishna151** [comment]
Name : Krishna Rajagopal
![image](https://user-images.githubusercontent.com/60443220/173266163-ef253d48-b8ee-4e8b-97e0-cae79818ea72.png)
![image](https://user-images.githubusercontent.com/60443220/173266493-0bdaa9bc-aaff-4f25-9723-385775d4cb1d.png)

Observations:

- Two separate charts are used to differentiate positive and negative gram staining 
- The effectiveness of each antibiotic against each bacteria is mapped using radar charts
- Logarithmic scale and reversal of the scale were done to depict the minimum inhibitory concentration (MIC) on the outside of the radar chart to ease graph interpretation.
- Higher effectiveness of Neomycin and Streptomycin against bacteria for negative gram staining
- Penicillin and Neomycin are more effective against  bacteria for positive gram staining

**Comment by Aviral0** [comment]
<img width="1200" alt="Screenshot 2022-06-13 at 8 12 42 AM" src="https://user-images.githubusercontent.com/69682322/173270160-245feccd-ba8e-4dae-bacf-2fdbcb43d089.png">
Observations:

- Two separate charts are used to differentiate positive and negative gram staining

- I wanted to make sure that the user viewing the graph should be able to read and identify the best drug against each bacteria

- I used the log 10 scale as the values of MIC concentration of Penicilin varied in higher magnitudes

- I used two different types of graphs to see which graph is easier read, one is trend line and the other is clustered histograms

My whole thought process was to convey the fact that lower the MIC concentration the better the drug it is

**Comment by Santoshsrini** [comment]
Name : R Santosh Srinivas
Assignment 2

![gram positive](https://user-images.githubusercontent.com/28926309/173274343-5b9ffdbc-adb4-44f3-817b-62adeb64ee63.png)
![gram negative](https://user-images.githubusercontent.com/28926309/173274397-95cf6a77-a7e4-461c-92c1-9e09ee4f53f1.png)


Description:

The visualization technique used is that of a horizontal bar graph with a logarithmic scale with the bacteria type on the Y axis and the MIC value on the X axis. 

MIC is plotted for the three different categories of drugs each depicted by a different color for effective comparison.  

Penicillin is effective for Gram Positive bacteria and Neomycin for gram negative bacteria. Effectiveness is measured by low concentrations of MIC. 

I used this method of visualization because at a glance one can know which drug is effective. The ones leaning towards the left ( MIC < 1 ) are more effective compared to the ones leaning towards the right ( MIC > 1) and this demarcation makes it visually easy to identify.

**Comment by Apharna** [comment]
BAR-GRAPH FPR POSITIVE STRAINS: 

![image](https://user-images.githubusercontent.com/68888128/173287047-f6d0376c-4a1b-4709-a840-f0b5e68a2f9c.png)

BAR-GRAPH FPR NEGATIVE STRAINS: 

![image](https://user-images.githubusercontent.com/68888128/173286998-875f0007-d9f4-4d1e-919f-abb94cea35f0.png)

COMMENTARY: 

Used a simple bar graph on the values sorted between Positive and Negative Strains. 
A Low value of MIC indicates higher effectiveness for the drug. 
Penicillin is effective in the case of positive strains and Neomycin for Negative strains

**Comment by arunimamor** [comment]
![image](https://user-images.githubusercontent.com/47169900/173432175-42480848-fee2-4bdd-917e-55ad22e2903a.png)
![image](https://user-images.githubusercontent.com/47169900/173432183-9a72a894-20a9-4994-b74d-f75db79bc33d.png)

Description : 

- Used two different graphs for positive and negative strains
- Had to use logarithmic scaling in order to normalize the high values 
-Lower the MIC value higher the effectiveness of the graph
     Most effective antibiotic for Positive Gram Staining bacteria  - Neomycin
     Most effective antibiotic for Negative Gram Staining bacteria  - Penicillin

**Comment by sarthak78** [comment]
Name: Sarthak Gupta
Assignment 2

<img width="620" alt="Screenshot 2022-06-14 at 6 01 43 PM" src="https://user-images.githubusercontent.com/33370930/173578389-c822ebef-5ab5-49a4-a89d-0a9f3a797ae9.png">
<img width="620" alt="Screenshot 2022-06-14 at 6 03 46 PM" src="https://user-images.githubusercontent.com/33370930/173578423-0385953a-ec1a-42b6-a46a-6178a2190427.png">

  I have used a horizontal bar graph with a logarithmic scale reflecting the effect on the Y-axis and the type of bacteria on the X-axis.
I have also shown the different bacteria effects on the type of vaccine.
The purpose is to show the effect of all the bacteria on different vaccines to easily categorize their effect

Results:-

The most effective vaccine for most of the Positive Gram Straining bacteria: Neomycin
The most effective vaccine for most of the Negative Gram Straining bacteria: Penicillin

**Comment by sundaramgupta** [comment]
For Positive Gram Straining bacteria Neomycin is the best
For Negative Gram Straining bacteria, Penicillin is the best

![pos](https://user-images.githubusercontent.com/50690766/173600494-f88f4e03-bc30-40de-82d2-bce10384f75e.png)
![neg](https://user-images.githubusercontent.com/50690766/173600517-404b993f-f6df-495f-9881-7d732c54ecf5.png)

**Comment by blessondavis** [comment]
![gollu_bargraph](https://user-images.githubusercontent.com/94608413/173680352-4baf6789-3bc3-4ca6-9c43-92795e20a973.jpg)
![gollu_bargraph-ve](https://user-images.githubusercontent.com/94608413/173680363-5a7b9a21-659a-41e7-ada7-c23d895ecaf1.jpg)

Name: Blesson Davis

1. The idea of taking each bacteria is to compare the effectiveness of the antibiotics. 
2. MIC might be jargon for the public, hence I mentioned that the lesser, the better in the graph.
3. I made sure the bars are adequately visible by selecting the appropriate background colour.
4. It matters a lot to whom this is presented. Scientific communities might find this graph easy to understand while a common person might not be about to grasp the depth of the data. 
5. Scaling was done to make a fair representation.

Also by showing the numbers on the bar, I wanted the person to know the exact value.

**Comment by rishi456187** [comment]
![Picture2](https://user-images.githubusercontent.com/94710987/173739429-90e92d04-652a-4340-806f-daeb7e6edbf1.png)
![Picture1](https://user-images.githubusercontent.com/94710987/173739437-0d1f416b-3f96-4723-9ba7-22e0f49bb4e4.png)

Name Rishi Khandelwal
1. the effects of all three drugs are color coded and log transformed. 
2. the bacteria against which the effect of a drug is measured is mentioned on the chart itself. 
3. postive and negative gram straining are represented differently so as to improve readability.
